name: Deploy
on:
  push:
    branches:
    - main
    - deploy-action
    
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
  
      - name: Deploy 
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: '${{ secrets.SSH_USERNAME }}'
          server: '${{ secrets.HOST }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist/*'
          remote_path: '/home/${{ secrets.SSH_USERNAME }}/dist'

      - name: SSH access
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.SSH_SUDO_PASSWORD }} | sudo -S su -c 'export PORT=80'
            echo ${{ secrets.SSH_SUDO_PASSWORD }} | sudo -S su -c 'export NODE_ENV=production'
            echo ${{ secrets.SSH_SUDO_PASSWORD }} | sudo -S su -c 'export YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}'

            echo ${{ secrets.SSH_SUDO_PASSWORD }} | sudo -S su -c 'pm2 list'

            echo ${{ secrets.SSH_SUDO_PASSWORD }} | sudo -S su -c 'pm2 start dist/bio/server/server.mjs -i max --name server'

            echo ${{ secrets.SSH_SUDO_PASSWORD }} | sudo -S su -c 'pm2 list'
             
        
      
